FROM node:lts-alpine AS runtime
WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321

ARG SUPABASE_URL=${SUPABASE_URL}
ARG SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

ENV SUPABASE_URL=${SUPABASE_URL}
ENV SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

EXPOSE 4321

CMD node ./dist/server/entry.mjs